### ISSUE TITLE
Shootable button (type door) for e4m5 secret is not lit in copper 1.30

### ISSUE THREAD

**Issue by wirion** [itslunaranyo/copper#19]
Shootable button (type door) for e4m5 secret is not lit. This is copper 1.30 in ironwail 0.7 and quakespasm 0.96.1, I don't know if the bug is present in earlier versions.

![e4m5_2024-01-17_04-36-09](https://github.com/itslunaranyo/copper/assets/1149836/90ad485b-ee19-4b51-8fb4-2395357720a4)
![e4m5_2024-01-17_04-37-56](https://github.com/itslunaranyo/copper/assets/1149836/abddcceb-3b01-4d1f-9655-563cd7337d84)

**Comment by itslunaranyo** [comment]
For some reason the button, which is indeed actually a func_door, has a 'style' key (36), even though this did nothing in the vanilla game. What it does in copper is turn off the spotlight highlighting the button, because the style key matches that light and because the "door" starts "closed".

When you shoot it and it "opens", it turns on the light, but also triggers the light as normal and turns it off during the same frame, so it's never on.

Style keys for triggered lights were added by the compiler and mappers never had to touch them, so I have no idea why Petersen added that key to that door-button, or how he knew the value was 36. It couldn't have been a compiler bug from the part of development when this map was compiled for the last time because there's a second func_door/light combo matching this one (the silver key button at the exit) that doesn't have the same problem.

So, whatever, I don't know. Door lightstyle control is already mature and in the wild and I can't undo it now, so this is fixed for 1.31 in the most painful way: a special-case check if the current map is named e4m5. :(

**Comment by wirion** [comment]
OMG that is so weird... sorry you had to deal with that. But thanks for the investigation and fix, however awkward it may be.
Maybe Petersen was experimenting with entities and keys, got the secret to work like that, and then just forgot about it.

And thank you so much for copper and udob!
